<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-11-29T06:00:18Z" name="Default suite" finished-at="2019-11-29T06:00:40Z" duration-ms="21993">
    <groups>
    </groups>
    <test started-at="2019-11-29T06:00:18Z" name="Default test" finished-at="2019-11-29T06:00:40Z" duration-ms="21993">
      <class name="PomPack.tests.LoginTest">
        <test-method signature="testLogin()[pri:0, instance:PomPack.tests.LoginTest@3b69e7d1]" started-at="2019-11-29T11:30:18Z" name="testLogin" finished-at="2019-11-29T11:30:39Z" duration-ms="20908" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Not sucessfully logined]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Not sucessfully logined
	at junit.framework.Assert.fail(Assert.java:47)
	at PomPack.tests.base.BaseTest.reportFail(BaseTest.java:76)
	at PomPack.tests.LoginTest.testLogin(LoginTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="testClosure()[pri:0, instance:PomPack.tests.LoginTest@3b69e7d1]" started-at="2019-11-29T11:30:39Z" name="testClosure" finished-at="2019-11-29T11:30:40Z" duration-ms="998" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClosure -->
      </class> <!-- PomPack.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
